name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings And Gentleman
        run: |
          echo "Hello world"
          echo "second line - multiline"
      - name: Say Goodbye
        run: echo "Bye Bye everyone" 
      
