name: Output
on: workflow_dispatch 
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Context
        run: echo "${{ toJSON(github) }}" 
      - name: Output Info
        run: |
          echo "Git Hash: $(git rev-parse HEAD)"
          echo "Node Version: $(node -v)"
          echo "NPM Version: $(npm -v)"